config/routes.rb
Rails.application.routes.draw do

	#root to: "pages#home"
	root to: "posts#index"
  

  	get "about", to: "pages#about"


  	get "contact", to: "pages#contact"



  #	get "post/new", to: "posts"new"
  #	post "post", to: "posts#create"

  	resources :posts, only: [:index, :show, :new, :create, :edit, :update, :destroy]



end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord

	belongs_to :post
	
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/viewcounter.rb
class Viewcounter < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ActionController::Base
 
  def create
  	post = Post.find(params[:post_id])
  	comment_params = params.required(:comment).permit(:author, :body)
  	post.comments.create(comment_params)
  	redirect_to post_path(id: post.id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def home
		@vc = Viewcounter.find(1)
		@vc.view_count+=1
		@vc.save


	end

	def about
		@vc= Viewcounter.find(2)
		@vc.view_count+=1
		@vc.save
	end

	def contact
		@vc = Viewcounter.find(3)
		@vc.view_count+=1
		@vc.save
	end



end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	def index
		@posts = Post.all
	end


	def show
		@post = Post.find(params[:id])
	end



	def new
		@post = Post.new
		
	end




	def create
		post_params = params[:post].permit(:title, :author, :content)
		post = Post.create(post_params)
		redirect_to post_path(id: post.id)
	end



	def edit
		@post = Post.find(params[:id])

	end


	def update
		post_params = params[:post].permit(:title, :author, :content)
		post = Post.find(params[:id])
		post.update(post_params)
		redirect_to post_path(id: post.id)
	
	end



	def destroy
		@post = Post.find(params[:id])
		@post.destroy
		redirect_to posts_path

	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Alphacampblogapp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

<!--  <div class='container'>
	<div class='row'>
		<div class='col-xs-4 col-xs-offset-4'>
    <%= yield %>

    	</div>
   </div>
</div>

-->

 <%= yield %>

  </body>
</html>

app/views/pages/about.html.erb
<h1>About</h1>

<%= link_to "home", root_path %>

<p>
<%= "#{@vc.view_count} views" %>
</p>

app/views/pages/contact.html.erb
<h1>contact</h1>







<%= link_to "home", root_path %>

<p>
<%= "#{@vc.view_count} views" %>
</p>

app/views/pages/home.html.erb
<h1>Hello World</h1>




<%= link_to "about", about_path %>
<%= link_to "contact", contact_path %>






<p>
<%= "#{@vc.view_count} views" %>
</p>

app/views/posts/edit.html.erb
<%= form_for @post, url: post_path(id: @post.id), method: :put do |f| %>

<div>
	<%= f.label  :title %>
	<%= f.text_field :title %>
</div>


<div>
	<%= f.label  :author %>
  <%= f.text_field :author %>
</div>

<div>
  <%= f.label  :content %>
  <%= f.text_area :content %>
</div>


<div>
  <%= f.submit "Create" %>
</div>

<% end %>

app/views/posts/index.html.erb
	
	
	
	

	<tbody>

	
		<nav class="nav-main">
			<div class="logo">Regent C</div>
			<ul>
				
				<li>
					<label for="Profile" class="nav-item">Profile</label>
				</li>

				<li>
					<label for="Resume" class="nav-item">#</label>
				</li>
				<li>
					<label for="myWorks" class="nav-item">#</label>
				</li>
				<li>
					<label for="contactMe" class="nav-item">#</label>
				</li>
			</ul>
		</nav>


<div class="background-image">

			<div class="container">
				<h1 class="header-text">R.C</h1>
					<h2 class="h2">My Blog</h2>
			</div>

	<thead>
		<table class="h1">
		 <th>Title</th>
		 <th>Author</th>
		 <th>Created At</th>
		</table>
	</thead>


	<div class="container">
	  <table align="center">
	   <% @posts.each do |post|	%>
	  
		 <tr>
			<td>	
				<%= post.title	%>
			</td>
			<td>	
				<%= post.author %>
			</td>
			<td>	
				<%= post.content %>
			</td>
			<td>	
				<%= post.created_at %>
			</td>
			<td>	
				<%= link_to 'View', post_path(id: post.id) %>
			</td>


			<td>
				<%= link_to 'Destroy', post_path(id: post.id),
					method: :delete,
					data: { confirm: 'Are you sure?'} %>
			</td>

		 </tr>
	 
		<% end	%>	

		</table>

	</div>
		

	</tbody>
</table>


		


<%= link_to 'Create New Post', new_post_path %>

</div>

app/views/posts/new.html.erb
<%= form_for @post, url: posts_path, method: :post do |f| %>

<div>
	<%= f.label  :title %>
	<%= f.text_field :title %>
</div>


<div>
	<%= f.label  :author %>
  <%= f.text_field :author %>
</div>

<div>
  <%= f.label  :content %>
  <%= f.text_area :content %>
</div>


<div>
  <%= f.submit "Create" %>
</div>
<% end %>

app/views/posts/show.html.erb
<h1>Post show page</h1>


<h2> <%= @post.title %> </h2>

<p> <%= @post.author %> </p>

<p> <%= @post.content %> </p>

<%= link_to 'Edit', edit_post_path(id: @post.id) %>
<%= link_to 'Back to All Posts', posts_path(id: @post.id) %>